python-cn/firefly

.pre-commit-config.yaml
.travis.yml
dev-requirements.txt
firefly/models.py
firefly/static/javascripts/create_topic.js
firefly/static/javascripts/index.js
firefly/static/stylesheets/scss/common/body.scss
firefly/utils.py
setup.py

编辑窗口打开时初始化

---

.pre-commit-config.yaml
.travis.yml
README.md
firefly/static/javascripts/components/codemirror/mode/markdown/index.html
firefly/static/javascripts/components/codemirror/mode/markdown/test.js
firefly/static/javascripts/components/codemirror/mode/python/index.html
firefly/static/javascripts/components/codemirror/mode/ruby/index.html
firefly/static/javascripts/components/codemirror/mode/sql/index.html
firefly/static/javascripts/components/rawdeflate.js
firefly/static/stylesheets/scss/_skins.scss

* travis CI对pep8检查更严格
* fix项目的行尾空格问题

Travis pep

---

firefly/models.py
firefly/views/utils.py
requirements.txt

能正确处理单复数时间情况
ago:
1 minutes
now:
1 minute

使用arrow替代原有timesince实现

---

firefly/__init__.py
firefly/config.py
firefly/models.py
firefly/views/__init__.py
requirements.txt

使用flask-babel添加I18N语言支持，暂时只处理了时间。

---

CONTRIBUTORS.txt
README.md
firefly/models/Category.py
firefly/models/user.py

1. todo list 完成任务后回记录完成者的github id
2. 不再使用teambition && 鄙视teambition
3. 增加贡献者文件. 记录贡献者第一次贡献代码的时间等
效果可见: https://github.com/dongweiming/firefly/tree/update_readme

Update README & use trello instead of teambition

---

firefly/__init__.py
firefly/utils.py
firefly/views/home.py
firefly/views/post.py

change flask.ext. to flask_

---

firefly/static/javascripts/login.js
firefly/static/stylesheets/themes/zenburn.css
firefly/templates/base.html

imporve frontend

---

firefly/static/javascripts/accounts.js
firefly/templates/login.html
firefly/templates/posts/detail.html

可以通过登录或者注册使用第三方登录(其实支持github/google/twitter/facebook) 微博露出来但是其实没有实现

Enable oauth2

---

firefly/models/user.py
py2-requirements.txt

@halfcrazy 豆瓣的oauth2有点... 没有邮箱. 我只能对他和推特做额外的处理.

Fix Douban email

---

firefly/static/stylesheets/scss/home/body.scss
firefly/static/stylesheets/scss/home/topic-list.scss

Add home"s scss files

---

firefly/static/javascripts/keyboard.js

Missing keyboard.js

---

firefly/__init__.py
requirements.txt

后端接口改用flask-restful，添加flask-restful依赖

add dependency flask-restful

---

README.md

update todo list

---

firefly/views/category.py

fix "AttributeError: 'BaseList' object has no attribute 'order_by'"

fix AttributeError

---

firefly/views/api/__init__.py
firefly/views/api/user.py

大家觉得 unfollow 用什么 http 方法比较合适，

implement follow & unfollow user

---

firefly/views/api/category.py
firefly/views/api/consts.py
firefly/views/api/user.py
firefly/views/api/utils.py

我把创建的错误类型放到了consts.py里面 直接可以调用. 
http code:
```
GET: 200
POST: 201
PUT: 202
DELETE: 204
```

use builtin errorno for api status code

---

firefly/static/javascripts/common.js
firefly/static/javascripts/create_topic.js
firefly/static/javascripts/index.js
firefly/static/javascripts/libs/effeckt/list-items.js
firefly/static/stylesheets/effeckt/list-items.css
firefly/templates/index.html
firefly/templates/widgets/topic_item.html
firefly/views/api/category.py
firefly/views/home.py

1. 首页创建topic会有Effeckt.css效果
2. 修复通过名字过滤分类失效

effeckt for list item

---

firefly/views/api/user.py

ref to https://github.com/python-cn/firefly/commit/433e43c58009f2119eaf47674f2693840cf67113#commitcomment-11041860

fix user not found exception

---

.gitignore
firefly/static/javascripts/components/codemirror/lib/codemirror.js
firefly/static/javascripts/components/lib/codemirror.js

https://github.com/python-cn/firefly/issues/71 @halfcrazy @duoduo369 原因是这样:
```python
git check-ignore -v firefly/static/javascripts/components/codemirror/lib/codemirror.js
.gitignore:17:lib/	firefly/static/javascripts/components/codemirror/lib/codemirror.js
```

Fix .gitignore bugs

---

firefly/models/consts.py
firefly/models/topic.py
firefly/static/stylesheets/scss/common/body.scss
firefly/templates/posts/detail.html
firefly/templates/widgets/topic_item.html

Add category colors

---

firefly/static/stylesheets/scss/topic/topic.scss
firefly/templates/posts/detail.html
firefly/views/utils.py

主题页 加入一个short版本的timesince 模仿discourse

short_timesince

---

firefly/config.py
firefly/forms/user.py
firefly/models/user.py
firefly/templates/base.html
firefly/templates/login.html
firefly/views/home.py
tests/test_auth.py

没有使用 flask-security 内置的 login 和 register 的原因：
1. csrf_token 不兼容首页的登录框
2. 不兼容现有的 User 用户名和密码字段
大家觉得是否需要调整 `User` model:
* `name` -> `username`
* `encrypted_password` -> `password`

add login and register

---

firefly/models/user.py
firefly/views/api/user.py
tests/test_user.py

add test follow & block user

---

firefly/static/javascripts/create_comment.js
firefly/static/javascripts/create_topic.js
firefly/templates/widgets/markdown_editor.html
firefly/views/home.py
firefly/views/post.py
tests/test_post.py

finished topic comment

---

firefly/models/topic.py
firefly/templates/posts/detail.html

and adjust comment info on post detail page

change the default value of Comment.created_at from now to utcnow

---

tools/cleanup_branch.py

This script is used to clean up the branches which has not been updated a long time

Add cleanup_branch.py

---

firefly/static/javascripts/login.js

fix register password length problem, password length is required 8 bits

fix register password length problem

---

firefly/templates/login.html

@mozillazg @dongweiming 隐藏前端密码字段，

hide password field
